spring:
  application:
    name: READLY

  datasource:
    url: jdbc:postgresql://localhost:5432/readly
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
